[project]
name = "pyzacros"
dynamic = ["version", "dependencies", "optional-dependencies"]
description = "Python Library for Automating Zacros Simulations"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Nestor F. Aguirre", email = "aguirre@scm.com" },
    { name = "Pablo Lopez-Tarifa" },
    { name = "Software for Chemistry & Materials", email = "info@scm.com" }
]
maintainers = [
    { name = "Software for Chemistry & Materials", email = "info@scm.com" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords=["molecular modeling", "computational chemistry", "workflow", "python interface"]
# Dependencies are injected dynamically by scm_metadata_hook.py

[project.urls]
Homepage = "https://www.scm.com"
Documentation = "https://www.scm.com/doc/pyzacros/index.html"
GitHub = "https://github.com/SCM-NV/pyZacros"

[build-system]
requires = ["hatchling>=1.26", "hatch-vcs>=0.4.0", "setuptools-scm<9"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/scm"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/scm/pyzacros/version.py"

[tool.hatch.metadata.hooks.custom]
path = "scm_metadata_hook.py"

[tool.scm]
copy-to-target = ["examples/**/*", "tests/**/*", "../zacros_manual/ZacrosManual.pdf"]
copy-to-target-path-mappings = {"../zacros_manual/" = "doc/"}

[[tool.uv.index]]
name = "gitea"
url = "https://git.scm.com/api/packages/SCM/pypi/simple"
publish-url = "https://git.scm.com/api/packages/SCM/pypi"
explicit = true
