#!/bin/bash

singleTargetFile=$1

files=`cat ipynb_FILES`

cat << EOF > __preprocess.py
from nbconvert.preprocessors import Preprocessor

class CutLongOutputFiles(Preprocessor):

    def preprocess_cell(self, cell, resources, index):

        # Check if the cell has tags
        if cell.metadata.get('tags'):

            # Iterate over the tags
            for tag in cell.metadata.get('tags'):

                # Check if the cell has a tag starting with "cut_output"
                if tag.startswith('cut_output='):

                    # if so, get the parameters ntop and nbottom from the tag name
                    (ntop,nbottom) = map( int, tag.replace('cut_output=','').split('_') )

                    # Then, we just remove the lines in between ntop and nbottom
                    for item in cell['outputs']:
                        if item['name'] == 'stdout':
                            final_text = ""

                            lines = item.text.splitlines()
                            for i,line in enumerate(lines):
                                if i<ntop or i>=len(lines)-nbottom:
                                    final_text += line+'\n'
                                if i==ntop:
                                    final_text += '\n...\n\n'

                            item.text = final_text[:-1]

        return cell, resources

class RemoveHiddenCells(Preprocessor):

    def preprocess_cell(self, cell, resources, index):

        # Check if the cell has the tag "hide", if so
        # we just replace its text for nothing
        if "hide" in cell.get('metadata', {}).get('tags', []):
            cell['source'] = ""

        return cell, resources

class RemoveHtmlBase64Images(Preprocessor):

    def preprocess_cell(self, cell, resources, index):

        # Check if the cell has the tag "html_base64_image", if so
        # we just replace its text for EMBEDDED_IMAGE
        if "html_base64_image" in cell.get('metadata', {}).get('tags', []):
            cell['source'] = "![](EMBEDDED_IMAGE)"

        return cell, resources

class PreserveHTML(Preprocessor):
    def preprocess_cell(self, cell, resources, index):

        # Check if the cell has the tag "html_base64_image"
        if "html_base64_image" in cell.get('metadata', {}).get('tags', []):

            # If the cell is a Markdown with <img>
            if cell.cell_type == 'markdown' and '<img' in cell.source:
                # We wrap the content so that RST treats it as raw HTML.
                # Indentation is vital for RST to recognize it.
                html_content = cell.source.replace('\n', '\n   ')
                cell.source = f".. raw:: html\n\n   {html_content}"

                # Now, we change the type to 'raw' so that nbconvert
                # does not process it as MD
                cell.cell_type = 'raw'

        return cell, resources

EOF

for file in $files
do
    fileName=${file##.*/}
    filePath=`echo $file | sed 's/\/'$fileName'//g'`

    [ -n "$singleTargetFile" -a "$fileName" != "$singleTargetFile" ] && continue

    # Converts the .ipynb to .py in its own directory
    $AMSBIN/amspython -m nbconvert --Exporter.preprocessors="__preprocess.RemoveHtmlBase64Images" --to script --no-prompt "${filePath}/${fileName}"
    sed -i '1,2d' "${filePath}/${fileName%.ipynb}".py
    sed -i '1s/^/# This file was automatically generated by build-ipynb_FILES.sh from\n# the '${fileName}' file. All changes to this file will be lost\n/' "${filePath}/${fileName%.ipynb}".py

    cp "${filePath}/${fileName}" .

    # Converts the .ipynb to rst in this directory
    $AMSBIN/amspython -m nbconvert --Exporter.preprocessors="__preprocess.RemoveHiddenCells" \
        --Exporter.preprocessors="__preprocess.PreserveHTML" --Exporter.preprocessors="__preprocess.CutLongOutputFiles" --to rst ${fileName}
    mv ${fileName%.ipynb}.rst ${fileName%.ipynb}.rst.include
    sed -i 's#/.*/pyzacros/#/home/user/pyzacros/#g' "${fileName%.ipynb}.rst.include"

    rm ${fileName}
done

rm __preprocess.py
